name: CI local_test
on:
  workflow_dispatch:
  pull_request:
  release:
    types: [published]
  push:
    branches: ["main"]
    tags: ["*"]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}${{ github.event_name == 'release' && '-release' || '' }}
  cancel-in-progress: true

jobs:
  local_test:
    strategy:
      fail-fast: false
      matrix:
        version: ["1.7.0", "1.9.0", "1.11.0", "latest"]
        os: [ ubuntu-22.04, ubuntu-latest, windows-2022, windows-latest, macos-14, macos-latest ]
    runs-on: ${{ matrix.os }}
    env:
      TERM: xterm
    name: local
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v4
      - name: Setup Bats and Bats libs
        id: setup-bats
        uses: ./
        with:
          bats-version: ${{ matrix.version }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: "Set path env vars"
        shell: bash
        run: |
          set -eu
          BATS_LIB_PATH="$HOME/.local/share/bats"
          TEMPDIR="$RUNNER_TEMP/bats"
          if [[ "$RUNNER_OS" == "Windows" ]]; then
          TEMPDIR="$(cygpath --unix "$TEMPDIR")"
          fi
          (
            echo "BATS_LIB_PATH=$BATS_LIB_PATH"
            echo "TEMPDIR=$TEMPDIR"
          ) >> $GITHUB_ENV

      - name: Check bats libs source path
        shell: bash
        run: |
          set -eu
          [[ -d "${TEMPDIR}/bats-support" ]] || echo "DOWNLOAD_BATS_SUPPORT=1">>${GITHUB_ENV}
          [[ -d "${TEMPDIR}/bats-assert" ]] || echo "DOWNLOAD_BATS_ASSERT=1">>${GITHUB_ENV}
          [[ -d "${TEMPDIR}/bats-detik" ]] || echo "DOWNLOAD_BATS_DETIK=1">>${GITHUB_ENV}
          [[ -d "${TEMPDIR}/bats-file" ]] || echo "DOWNLOAD_BATS_FILE=1">>${GITHUB_ENV}
      - name: Set cache for Bats-support source
        if: env.DOWNLOAD_BATS_SUPPORT == '1'
        uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v4
        id: support-source-cache
        with:
          path: ${{ steps.setup-bats.outputs.tmp-path }}/bats-support
          key: ${{ runner.os }}-${{ runner.arch }}-bats-support-${{ steps.setup-bats.outputs.support-version }}-source
      - name: Download Bats-support source
        if: env.DOWNLOAD_BATS_SUPPORT == '1' && steps.support-source-cache.outputs.cache-hit != 'true'
        shell: bash
        env:
          VERSION: ${{ steps.setup-bats.outputs.support-version }}
          TEMPDIR: ${{ env.TEMPDIR }}/bats-support
        run: |
          ./download-bats-lib.sh  'bats-core/bats-support'  "$VERSION"  "$TEMPDIR"
      - name: Set cache for Bats-assert source
        if: env.DOWNLOAD_BATS_ASSERT == '1'
        uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v4
        id: assert-source-cache
        with:
          path: ${{ steps.setup-bats.outputs.tmp-path }}/bats-assert
          key: ${{ runner.os }}-${{ runner.arch }}-bats-assert-${{ steps.setup-bats.outputs.assert-version }}-source
      - name: Download Bats-assert source
        if: env.DOWNLOAD_BATS_ASSERT == '1' && steps.assert-source-cache.outputs.cache-hit != 'true'
        shell: bash
        env:
          VERSION: ${{ steps.setup-bats.outputs.assert-version }}
          TEMPDIR: ${{ env.TEMPDIR }}/bats-assert
        run: |
          ./download-bats-lib.sh  'bats-core/bats-assert'  "$VERSION"  "$TEMPDIR"
      - name: Set cache for Bats-detik source
        if: env.DOWNLOAD_BATS_DETIK == '1'
        uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v4
        id: detik-source-cache
        with:
          path: ${{ steps.setup-bats.outputs.tmp-path }}/bats-detik
          key: ${{ runner.os }}-${{ runner.arch }}-bats-detik-${{ steps.setup-bats.outputs.detik-version }}-source
      - name: Download Bats-detik source
        if: env.DOWNLOAD_BATS_DETIK == '1' && steps.detik-source-cache.outputs.cache-hit != 'true'
        shell: bash
        env:
          VERSION: ${{ steps.setup-bats.outputs.detik-version }}
          TEMPDIR: ${{ env.TEMPDIR }}/bats-detik
        run: |
          ./download-bats-lib.sh  'bats-core/bats-detik'  "$VERSION"  "$TEMPDIR"
      - name: Set cache for Bats-file source
        if: env.DOWNLOAD_BATS_FILE == '1'
        uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v4
        id: file-source-cache
        with:
          path: ${{ steps.setup-bats.outputs.tmp-path }}/bats-file
          key: ${{ runner.os }}-${{ runner.arch }}-bats-file-${{ steps.setup-bats.outputs.file-version }}-source
      - name: Download Bats-file source
        if: env.DOWNLOAD_BATS_FILE == '1' && steps.file-source-cache.outputs.cache-hit != 'true'
        shell: bash
        env:
          VERSION: ${{ steps.setup-bats.outputs.file-version }}
          TEMPDIR: ${{ env.TEMPDIR }}/bats-file
        run: |
          ./download-bats-lib.sh  'bats-core/bats-file'  "$VERSION"  "$TEMPDIR"

      - name: Execute test to check Bats-support
        shell: bash
        env:
          TEMPDIR: ${{ env.TEMPDIR }}/bats-support
        run: |
          cd ${TEMPDIR}
          bats test
      - name: Execute test to check  Bats-assert
        shell: bash
        env:
          TEMPDIR: ${{ env.TEMPDIR }}/bats-assert
        run: |
          cd ${TEMPDIR}
          bats test
      - name: Execute test to check Bats-detik
        shell: bash
        continue-on-error: true
        env:
          TEMPDIR: ${{ env.TEMPDIR }}/bats-detik
        run: |
          cd ${TEMPDIR}
          bats tests
      - name: Execute test to check Bats-file
        shell: bash
        # Currently the bats-file tests are broken
        # in gh runner env
        continue-on-error: true
        env:
          TEMPDIR: ${{ env.TEMPDIR }}/bats-file
        run: |
          cd ${TEMPDIR}
          bats test
      - name: Execute example tests
        shell: bash
        run:
          bats -T -p tests

  local_test_trigger_cache:
    needs: [local_test]
    strategy:
      fail-fast: false
      matrix:
        version: ["1.7.0", "1.9.0", "1.11.0", "latest"]
        os: [ ubuntu-22.04, ubuntu-latest, windows-2022, windows-latest, macos-14, macos-latest ]
    runs-on: ${{ matrix.os }}
    env:
      TERM: xterm
    name: local-default-no-cache
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v4
      - name: Setup Bats and Bats libs
        uses: ./
        id: setup-bats
        with:
          bats-version: ${{ matrix.version }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Execute example tests
        shell: bash
        run:
          bats -T -p tests
